coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 0%

comment:
  layout: "condensed_header, diff, flags, components, files"

ignore:
  - "tests/**"
  - "examples/**"
  - "**/__init__.py"

codecov:
  require_ci_to_pass: true
